Adding the listener.
Brightspace/nunit-progress-reporter pull request #1
Opened 2017-03-02 23:20 UTC by saquibmian

This is a work in progress, but pushing for code review.
For niceness, run NUnit.Console with `--out=out.txt --err=err.txt --labels=Off`.

To deploy:
Simply install the nuget package beside the `NUnit.ConsoleRunner` package. The runner will look for any extensions under `NUnit.Extensions.*/tools/*.dll`.

Still needs unit tests.

2017-03-02 23:21 UTC, saquibmian commented
@JeffAshton still needs work polishing (unit tests, nuget publishing), but it works.

2017-03-02 23:25 UTC, JeffAshton requested changes

2017-03-02 23:25 UTC, JeffAshton commented on NUnit.Extension.AssemblyProgressReporter/AssemblyProgressReporterListener.cs
> +			if( !File.Exists( suite ) ) {
See if you can do something with just the path.  Pinging the file system is relatively far more expensive

2017-03-03 18:16 UTC, JeffAshton commented on NUnit.Extension.AssemblyProgressReporter/TestSuiteMessage.cs
> +			Enum.TryParse( reader.GetAttribute( "type" ), out tst );
Not checking result of TryParse, so you'll just get the first value.  Always check your try results

2017-03-03 18:16 UTC, JeffAshton commented on NUnit.Extension.AssemblyProgressReporter/TestSuiteMessage.cs
> +		public TestSuiteType? Type { get; private set; }
don't need private set; since you're only setting in constructor

2017-03-03 18:17 UTC, JeffAshton commented on NUnit.Extension.AssemblyProgressReporter/AssemblyProgressReporterListener.cs
> +					OnSuiteStarted( message as StartSuiteMessage );
nit:  here you would actually want cast.  Shouldn't downcast to null

2017-03-03 18:19 UTC, JeffAshton commented on NUnit.Extension.AssemblyProgressReporter/XmlMessage.cs
> +		public XmlMessage( XmlNode node ) {
Not used?

2017-03-03 18:28 UTC, saquibmian commented on NUnit.Extension.AssemblyProgressReporter/XmlMessage.cs
> +		public XmlMessage( XmlNode node ) {
Fixed. Forgot to delete this.

2017-03-03 18:28 UTC, saquibmian commented on NUnit.Extension.AssemblyProgressReporter/AssemblyProgressReporterListener.cs
> +					OnSuiteStarted( message as StartSuiteMessage );
Yes, better than null. Fixed.

2017-03-03 18:29 UTC, saquibmian commented on NUnit.Extension.AssemblyProgressReporter/TestSuiteMessage.cs
> +		public TestSuiteType? Type { get; private set; }
Fixed, also forgot to delete.

2017-03-03 18:29 UTC, saquibmian commented on NUnit.Extension.AssemblyProgressReporter/TestSuiteMessage.cs
> +			Enum.TryParse( reader.GetAttribute( "type" ), out tst );
Good catch. I got fooled by the nullable, but `tst` is not nullable.

2017-03-03 18:36 UTC, saquibmian commented on appveyor.yml
> +  account_feed: true
project_feed: true
account_feed is bad

2017-03-03 19:21 UTC, JeffAshton approved these changes

2017-03-03 19:23 UTC, merged